/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatesRouteImport } from './routes/states'
import { Route as AccountSavedRouteImport } from './routes/account.saved'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as AdminJurisdictionsRouteImport } from './routes/admin.jurisdictions'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminUsageRouteImport } from './routes/admin.usage'
import { Route as DeedStateRouteImport } from './routes/deed.$state'
import { Route as AccountDeedIdRouteImport } from './routes/account.deed.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSavedRoute = AccountSavedRouteImport.update({
  id: '/account/saved',
  path: '/account/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJurisdictionsRoute = AdminJurisdictionsRouteImport.update({
  id: '/admin/jurisdictions',
  path: '/admin/jurisdictions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/admin/usage',
  path: '/admin/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const DeedStateRoute = DeedStateRouteImport.update({
  id: '/deed/$state',
  path: '/deed/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeedIdRoute = AccountDeedIdRouteImport.update({
  id: '/account/deed/$id',
  path: '/account/deed/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/states': typeof StatesRoute
  '/account/saved': typeof AccountSavedRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/jurisdictions': typeof AdminJurisdictionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/deed/$state': typeof DeedStateRoute
  '/admin/': typeof AdminIndexRoute
  '/account/deed/$id': typeof AccountDeedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/states': typeof StatesRoute
  '/account/saved': typeof AccountSavedRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/jurisdictions': typeof AdminJurisdictionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/deed/$state': typeof DeedStateRoute
  '/admin': typeof AdminIndexRoute
  '/account/deed/$id': typeof AccountDeedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/states': typeof StatesRoute
  '/account/saved': typeof AccountSavedRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/jurisdictions': typeof AdminJurisdictionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/deed/$state': typeof DeedStateRoute
  '/admin/': typeof AdminIndexRoute
  '/account/deed/$id': typeof AccountDeedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/states'
    | '/account/saved'
    | '/account/settings'
    | '/admin/accounts'
    | '/admin/jurisdictions'
    | '/admin/login'
    | '/admin/subscriptions'
    | '/admin/usage'
    | '/deed/$state'
    | '/admin/'
    | '/account/deed/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/states'
    | '/account/saved'
    | '/account/settings'
    | '/admin/accounts'
    | '/admin/jurisdictions'
    | '/admin/login'
    | '/admin/subscriptions'
    | '/admin/usage'
    | '/deed/$state'
    | '/admin'
    | '/account/deed/$id'
  id:
    | '__root__'
    | '/'
    | '/states'
    | '/account/saved'
    | '/account/settings'
    | '/admin/accounts'
    | '/admin/jurisdictions'
    | '/admin/login'
    | '/admin/subscriptions'
    | '/admin/usage'
    | '/deed/$state'
    | '/admin/'
    | '/account/deed/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatesRoute: typeof StatesRoute
  AccountSavedRoute: typeof AccountSavedRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminJurisdictionsRoute: typeof AdminJurisdictionsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsageRoute: typeof AdminUsageRoute
  DeedStateRoute: typeof DeedStateRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AccountDeedIdRoute: typeof AccountDeedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/saved': {
      id: '/account/saved'
      path: '/account/saved'
      fullPath: '/account/saved'
      preLoaderRoute: typeof AccountSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jurisdictions': {
      id: '/admin/jurisdictions'
      path: '/admin/jurisdictions'
      fullPath: '/admin/jurisdictions'
      preLoaderRoute: typeof AdminJurisdictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deed/$state': {
      id: '/deed/$state'
      path: '/deed/$state'
      fullPath: '/deed/$state'
      preLoaderRoute: typeof DeedStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/deed/$id': {
      id: '/account/deed/$id'
      path: '/account/deed/$id'
      fullPath: '/account/deed/$id'
      preLoaderRoute: typeof AccountDeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatesRoute: StatesRoute,
  AccountSavedRoute: AccountSavedRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AdminAccountsRoute: AdminAccountsRoute,
  AdminJurisdictionsRoute: AdminJurisdictionsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsageRoute: AdminUsageRoute,
  DeedStateRoute: DeedStateRoute,
  AdminIndexRoute: AdminIndexRoute,
  AccountDeedIdRoute: AccountDeedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
